services:
  app:
    container_name: madr
    build: 
      context: . 
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: ${SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    restart: unless-stopped
    entrypoint: ./scripts/docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17.4-alpine3.21
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}"]
          interval: 5s
          timeout: 5s
          retries: 1

volumes:
  db_volume:
