"""Add unique constraints for name and isbn and year for books

Revision ID: 93584b655c7d
Revises: a38fdd145d83
Create Date: 2025-08-17 17:25:33.515541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93584b655c7d'
down_revision: Union[str, Sequence[str], None] = 'a38fdd145d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_author_name'), 'author', ['name'])
    op.add_column('book', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('book', sa.Column('year', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_book_name'), 'book', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_book_name'), 'book', type_='unique')
    op.drop_column('book', 'year')
    op.drop_column('book', 'isbn')
    op.drop_constraint(op.f('uq_author_name'), 'author', type_='unique')
    # ### end Alembic commands ###
