name: Testes de integração
on:
  push: 
    branches: 
     - main


jobs:
  unit-tests: 
    name: Executa testes
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.13"
    env:
      DATABASE_USER: "stub"
      DATABASE_PASSWORD: "stub"
      DATABASE_NAME: "stub"
      JWT_EXPIRATION_TIME: 1
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v6
      with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
    - run: poetry sync 
    - run: poetry run pytest

